apiVersion: v1
data:
  MYSQL_DATABASE: Y3VzdG9tZGI=
  MYSQL_PASSWORD: cGFzcw==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_USER: dXNlcg==
  MYSQL_DB: Y3VzdG9tZGI=
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
